#!/usr/bin/env python3
"""
Build `webpage/data/manifest.json` and the per-material tar indexes used by
the dataset viewer.

The webpage is fully static; this tool only runs locally when you want to
change which materials appear in the preview grid or refresh the tar index
files. Output goes into the `webpage/data/` directory and is loaded by the
browser at runtime.

Usage
-----
    python3 webpage/tools/build_manifest.py \\
        [--ids 156 249 309 428 483 2 8 20 35 50 ...] \\
        [--no-index]            # skip tar index generation (faster)
        [--out webpage/data]

Defaults to 20 hand-picked test-list materials with a mix of sample/ and
full materials/.

The tar index is generated by issuing many small HTTP Range requests to
the HuggingFace CDN to read each ustar header. Each material has 500-585
files, so this is a few thousand range requests. It runs fully in parallel
threads but still takes ~30s per material — that's why this is a build-
time tool, not a runtime cost the browser pays.
"""

import argparse
import concurrent.futures as cf
import json
import os
import sys
import urllib.request
from io import BytesIO
from pathlib import Path


HF_BASE = "https://huggingface.co/datasets/koalapenguin/RoboCloth/resolve/main"


# --------------------------------------------------------------------------
# Default preview list — mix of sample/ subset (5) and varied full materials.
# Ordered to span the catalogue so the grid looks interesting.
# --------------------------------------------------------------------------
DEFAULT_SAMPLE_IDS = [156, 249, 309, 428, 483]
DEFAULT_FULL_IDS   = [2, 8, 20, 35, 50, 84, 96, 109, 130, 145, 170, 190, 220, 350, 400]


def http_get(url: str, range_=None, timeout=30) -> bytes:
    req = urllib.request.Request(url)
    if range_:
        a, b = range_
        req.add_header("Range", f"bytes={a}-{b-1}")
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read()


def http_head_size(url: str) -> int:
    """Resolve the redirect chain to get the final Content-Length."""
    req = urllib.request.Request(url, method="HEAD")
    with urllib.request.urlopen(req, timeout=30) as r:
        return int(r.headers.get("Content-Length", "0"))


def parse_octal(b: bytes) -> int:
    s = b.split(b"\x00", 1)[0].split(b" ", 1)[0].strip()
    return int(s, 8) if s else 0


def parse_string(b: bytes) -> str:
    return b.split(b"\x00", 1)[0].decode("ascii", "replace")


def scan_tar_index(url: str, total: int = None, verbose=False) -> dict:
    """
    Walk the tar's headers via Range and produce {filename: [offset, size]}.

    Uses a sliding window: at each header position we Range-fetch 512 bytes,
    parse the header, then jump past the data (which is 512-aligned).
    """
    if total is None:
        total = http_head_size(url)
    index = {}
    cursor = 0
    zero_blocks = 0
    n = 0

    while cursor < total:
        buf = http_get(url, (cursor, cursor + 512))
        if len(buf) < 512:
            break
        if buf == b"\x00" * 512:
            zero_blocks += 1
            cursor += 512
            if zero_blocks >= 2:
                break
            continue
        zero_blocks = 0

        name = parse_string(buf[0:100])
        size = parse_octal(buf[124:136])
        prefix = parse_string(buf[345:500])
        typeflag = chr(buf[156]) if buf[156] else "0"
        full_name = f"{prefix}/{name}" if prefix else name

        if size > 0 and typeflag in ("0", "\x00"):
            # Store both the full archive path AND the basename, so the
            # browser can look up scan_log filenames (no `hdr/` prefix)
            # directly. Tars from this dataset use a `hdr/` directory.
            index[full_name] = [cursor + 512, size]
            base = full_name.split("/")[-1]
            if base != full_name and base not in index:
                index[base] = [cursor + 512, size]
        padded = ((size + 511) // 512) * 512
        cursor += 512 + padded
        n += 1
        if verbose and n % 50 == 0:
            print(f"    [{n:4d}] @ {cursor/1e9:.2f}/{total/1e9:.2f} GB", flush=True)

    return index


def fetch_scan_log_first_filename(material_id: int, sample: bool) -> str | None:
    folder = f"sample/material_{material_id}" if sample else f"materials/{material_id}"
    url = f"{HF_BASE}/{folder}/scan_log.json"
    try:
        body = http_get(url)
    except Exception as e:
        print(f"  [{material_id}] scan_log fetch failed: {e}")
        return None
    scan = json.loads(body)
    # Pick a "good" thumbnail: prefer a frame that's roughly mid-trajectory
    # and a popular light, so the cloth is well-illuminated.
    if not scan:
        return None
    # Sort by camera_id, pick the middle one with light_id 0
    by_cam = sorted(scan, key=lambda e: (e.get("light_id", 0), e.get("camera_id", 0)))
    middle = by_cam[len(by_cam) // 2]
    return middle["filename"]


def build_for_material(mid: int, sample: bool, out_dir: Path, want_index: bool):
    entry = {
        "id": mid,
        "sample_folder": sample,
        "label": "Sample subset" if sample else "Full capture",
    }
    fn = fetch_scan_log_first_filename(mid, sample)
    if fn:
        entry["thumb"] = {"filename": fn}

    if want_index:
        folder = f"sample/material_{mid}" if sample else f"materials/{mid}"
        tar_url = f"{HF_BASE}/{folder}/hdr.tar"
        idx_path = out_dir / "tar_index" / f"{mid}.json"
        if idx_path.exists() and idx_path.stat().st_size > 200:
            print(f"  [{mid}] tar index already exists, skipping")
        else:
            print(f"  [{mid}] scanning tar headers (this is slow)…")
            try:
                idx = scan_tar_index(tar_url)
                idx_path.parent.mkdir(parents=True, exist_ok=True)
                idx_path.write_text(json.dumps(idx))
                print(f"  [{mid}] -> {len(idx)} files, "
                      f"{idx_path.stat().st_size/1024:.1f} KB")
            except Exception as e:
                print(f"  [{mid}] tar index FAILED: {e}")

    return entry


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ids", nargs="*", type=int, default=None,
                    help="Material IDs to include (mix of sample + full)")
    ap.add_argument("--samples", nargs="*", type=int,
                    default=DEFAULT_SAMPLE_IDS,
                    help="IDs that live in sample/material_X/")
    ap.add_argument("--no-index", action="store_true",
                    help="Skip generating tar indexes")
    ap.add_argument("--out", default="webpage/data",
                    help="Output directory (default: webpage/data)")
    ap.add_argument("--workers", type=int, default=4,
                    help="Concurrent materials to process")
    args = ap.parse_args()

    if args.ids is None:
        ids = sorted(set(DEFAULT_SAMPLE_IDS + DEFAULT_FULL_IDS))
    else:
        ids = sorted(set(args.ids))

    sample_set = set(args.samples)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating manifest for {len(ids)} materials -> {out_dir}/manifest.json")
    print(f"  sample-folder ids: {sorted(sample_set & set(ids))}")
    print(f"  tar index: {'OFF' if args.no_index else 'ON'}")

    entries = []
    with cf.ThreadPoolExecutor(max_workers=args.workers) as ex:
        futs = {
            ex.submit(
                build_for_material, mid, mid in sample_set, out_dir,
                not args.no_index,
            ): mid for mid in ids
        }
        for fut in cf.as_completed(futs):
            mid = futs[fut]
            try:
                entries.append(fut.result())
            except Exception as e:
                print(f"  [{mid}] FAILED: {e}")

    entries.sort(key=lambda e: e["id"])
    out = {"preview": entries}
    (out_dir / "manifest.json").write_text(json.dumps(out, indent=2))
    print(f"Wrote {len(entries)} entries to {out_dir}/manifest.json")


if __name__ == "__main__":
    main()
