type: "MoeLatentModel"
latent_dim: 8
predict_frame: True
gt_frame: False
colorful_texture: True
leaky_relu: True
texture_resolution: 2048
hidden_layers: [128, 128, 64, 32, 16]
# hidden_layers: [256, 256, 128, 64, 32, 16]
Gaussian_blur: False
activation: "relu"
input_channels: 9

latent_texture_path: "/absolute/path/to/latent_texture.pt"

# neural geometry 
neural_geometry:
  enable: True
  latent_dim: 8
  hidden_layers: [16, 8, 4]
  output_channels: 2 # 2D uv offset
  local_wi_wo: False # Use local or global wi-wo
  positional_encoding: False # Use position encoding or not
  recompute_frame: False

moe:
  num_experts: 32
  moe_k: 2
  moe_hidden_size: 32
  moe_loss_coef: 1e-2
  pre_moe_hidden_dim: 128

# config 1:
#larger_latent_dim: True
#different_decoder: True
#output_channels: 1

# # config 2:
# larger_latent_dim: True
# different_decoder: False
# output_channels: 1

# # config 3:
larger_latent_dim: False
different_decoder: False
output_channels: 3
